// ignore_for_file: file_names

import 'atendee_model.dart';

final List<AttendeeModel> attendees = [
  const AttendeeModel(
    createdBy: 'createdBy1',
    id: 'id1',
    firstName: 'John',
    middleName: 'Doe',
    lastName: 'Smith',
    gender: 'Male',
    phoneNo: '1234567890',
    parentName: 'Jane Smith',
    parentNo: '9876543210',
    homeAddress: '123 Main St',
    disabilityCluster: 'None',
    commitmentFee: 'Paid',
    parentConsent: 'Yes',
    passIssued: 'Yes',
    wouldCamp: 'Yes',
  ),
  const AttendeeModel(
     createdBy: 'createdBy2',
    id: 'id2',
    firstName: 'Jane',
    middleName: 'Doe',
    lastName: 'Smith',
    gender: 'Female',
    phoneNo: '9876543210',
    parentName: 'John Smith',
    parentNo: '1234567890',
    homeAddress: '456 Elm St',
    disabilityCluster: 'Physical',
    commitmentFee: 'Paid',
    parentConsent: 'Yes',
    passIssued: 'No',
    wouldCamp: 'No',
  ),
  const AttendeeModel(
     createdBy: 'createdBy2',
    id: 'id2',
    firstName: 'Jesse',
    middleName: 'Oyofo',
    lastName: 'Dan',
    gender: 'Female',
    phoneNo: '9876543210',
    parentName: 'John Smith',
    parentNo: '1234567890',
    homeAddress: '456 Elm St',
    disabilityCluster: 'Physical',
    commitmentFee: 'Paid',
    parentConsent: 'Yes',
    passIssued: 'No',
    wouldCamp: 'No',
  ),
  const AttendeeModel(
     createdBy: 'createdBy2',
    id: 'id2',
    firstName: 'Jane',
    middleName: 'Doe',
    lastName: 'Smith',
    gender: 'Female',
    phoneNo: '9876543210',
    parentName: 'John Smith',
    parentNo: '1234567890',
    homeAddress: '456 Elm St',
    disabilityCluster: 'Physical',
    commitmentFee: 'Paid',
    parentConsent: 'Yes',
    passIssued: 'No',
    wouldCamp: 'No',
  ),
  const AttendeeModel(
     createdBy: 'createdBy2',
    id: 'id2',
    firstName: 'Jane',
    middleName: 'Doe',
    lastName: 'Smith',
    gender: 'Female',
    phoneNo: '9876543210',
    parentName: 'John Smith',
    parentNo: '1234567890',
    homeAddress: '456 Elm St',
    disabilityCluster: 'Physical',
    commitmentFee: 'Paid',
    parentConsent: 'Yes',
    passIssued: 'No',
    wouldCamp: 'No',
  ),
  const AttendeeModel(
     createdBy: 'createdBy2',
    id: 'id2',
    firstName: 'Jane',
    middleName: 'Doe',
    lastName: 'Smith',
    gender: 'Female',
    phoneNo: '9876543210',
    parentName: 'John Smith',
    parentNo: '1234567890',
    homeAddress: '456 Elm St',
    disabilityCluster: 'Physical',
    commitmentFee: 'Paid',
    parentConsent: 'Yes',
    passIssued: 'No',
    wouldCamp: 'No',
  ),
  const AttendeeModel(
     createdBy: 'createdBy2',
    id: 'id2',
    firstName: 'Jane',
    middleName: 'Doe',
    lastName: 'Smith',
    gender: 'Female',
    phoneNo: '9876543210',
    parentName: 'John Smith',
    parentNo: '1234567890',
    homeAddress: '456 Elm St',
    disabilityCluster: 'Physical',
    commitmentFee: 'Paid',
    parentConsent: 'Yes',
    passIssued: 'No',
    wouldCamp: 'No',
  ),

  // Add more AttendeeModel items here...
];
